language: generic
matrix:
    include:
        - os: linux
          env: GCC=gcc-5 CLANG=clang-3.8
          addons:
              apt:
                  packages:
                      - gcc-5
                      - clang-3.8
                      - valgrind
                  sources:
                      - llvm-toolchain-precise-3.8
                      - ubuntu-toolchain-r-test
script: make -C test check
